### ISSUE TITLE
JAR file should not contain resources

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist-apps-archetype#3]
I think there is no good reason to have all  kind of resources in the JAR file, as these are bundled in the XAR file already

![test____tmp_test__-_____xar-assembly_xml__test_](https://user-images.githubusercontent.com/1700062/34648603-511e8f6e-f39c-11e7-94f4-3680186463bc.png)

**Comment by adamretter** [comment]
This is normal. When you have `src/main/java` and `src/main/resources` all resources are required at run-time and so will be placed into the artifacts.

**Comment by dizzzz** [comment]
I can not see why these resources need to be in the JAR file,.... making the files availabe TWICE in the same XAR file !
  Lets have a chat ....

**Comment by adamretter** [comment]
@dizzzz If you think about it. You don't need the JAR file at all ;-)

**Comment by dizzzz** [comment]
Hmmm I lost you :( For Some things I really need a jar file. But as I bundle large resources, think of a few mb of images, why should that also be in the jar file?

**Comment by adamretter** [comment]
@dizzzz I think maybe it is better if we discuss in realtime chat/call what you are trying to package, so I can explain how that is best done with this.
