### ISSUE TITLE
kuberam-expath-plugin requires different approach support multiple Java modules

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist-apps-archetype#6]
Recently the `kuberam-expath-plugin` has changed to support multiple Java modules in one XAR file. The current `archetype` code does not support it (yet).

see https://github.com/claudius108/kuberam-expath-plugin/issues/7#issuecomment-356392734 

The xar-assembly.xml looks as following to support the multi-java-module :

```xml
    <components>
        <resource>
            <public-uri>https://my-organisation.com/exist-db/ns/app/my-java-module</public-uri>
            <file>com.my.ExampleModule</file>
        </resource>
<resource>
            <public-uri>https://my-organisation.com/exist-db/ns/app/my-java-module-2</public-uri>
            <file>com.my.ExampleModuleToo</file>
        </resource>
    </components>
```

**Comment by dizzzz** [comment]
Maybe.... we can get rid of the comments in pom.xml:

```xml
 <!-- unfortunately this is needed by kuberam-expath-plugin to successfully
                            generate its components.xml -->
```

**Comment by adamretter** [comment]
@claudius108 are these properties still required to generate the `components.xml`?

**Comment by claudius108** [comment]
No, for the java clasess needed for exist.xml.

**Comment by adamretter** [comment]
@dizzzz Okay so it sounds like we might still need this for the moment.

**Comment by dizzzz** [comment]
@adamretter as: we need to leave it there for the plugin but it has no function?

**Comment by adamretter** [comment]
@dizzzz I though @claudius108 said above it is needed for `exist.xml`!

**Comment by claudius108** [comment]
Sorry, for my English. They are not needed anymore, as they were needed ONLY for exist.xml.
