### ISSUE TITLE
how to use my own archetype

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/exist-apps-archetype#9]
I m looking into adding some frontend related features to the archetype, and i m stuck on something really silly. How do I generate an app with my development fork of the archetype instead of the official client?

I think this info would make a good addition to the readme.

**Comment by adamretter** [comment]
1. Make your changes locally
2. run `mvn install`
3. Generate an app using a SNAPSHOT version of the archetype
4. Rinse and repeat...
